# Generated by Django 4.2.6 on 2024-04-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('S', 'sedentary'), ('LA', 'lightly active'), ('MA', 'moderately active'), ('VA', 'very active'), ('EA', 'extra active')], default='sedentary', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('M', 'maintain weight'), ('GS', 'gain weight slowly'), ('GF', 'gain weighgt fast'), ('LS', 'lose weight slowly'), ('LF', 'lose weight fast')], default='maintain weight', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='male', max_length=20),
        ),
    ]
