# Generated by Django 4.2.6 on 2024-05-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_activity_level_profile_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('S', 'sedentary'), ('LA', 'lightly active'), ('MA', 'moderately active'), ('VA', 'very active'), ('EA', 'extra active')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('M', 'maintain weight'), ('GS', 'gain weight slowly'), ('GF', 'gain weight fast'), ('LS', 'lose weight slowly'), ('LF', 'lose weight fast')], default='M', max_length=40),
        ),
    ]
