# Generated by Django 4.2.6 on 2024-05-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_activity_level_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('S', 'sedentary'), ('LA', 'lightly active'), ('MA', 'moderately active'), ('VA', 'very active'), ('EA', 'extra active')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('M', 'maintain weight'), ('GS', 'gain weight slowly'), ('GF', 'gain weight fast'), ('LS', 'lose weight slowly'), ('LF', 'lose weight fast')], max_length=40),
        ),
    ]
