# Generated by Django 4.2.6 on 2024-07-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('accounts', '0012_alter_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.recipe'),
        ),
    ]
