# Generated by Django 4.2.6 on 2024-09-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_edamam_id'),
        ('accounts', '0013_profile_favorite_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorited_by', to='recipes.recipe'),
        ),
    ]
