# Generated by Django 4.2.6 on 2024-10-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_History',
            new_name='UserHistory',
        ),
    ]
