# Generated by Django 4.2.6 on 2024-11-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_user_history_userhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='created_at',
        ),
    ]
