# Generated by Django 4.2.6 on 2024-05-06 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('calories_goal', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Energy goal per day (KCAL)')),
                ('calories_today', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='kcal')),
                ('fats_goal', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Fats goal per day (g)')),
                ('fats_today', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='Fats(g)')),
                ('protein_goal', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Protein goal per day (g)')),
                ('protein_today', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='Protein(g)')),
                ('carbs_goal', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Carbohydrates goal per day (g)')),
                ('carbs_today', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='CARBS(g)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
