# Generated by Django 4.2.6 on 2024-05-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_height_profile_weight_and_more'),
        ('api', '0002_remove_daytrack_user_daytrack_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytrack',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='track', to='accounts.profile'),
        ),
    ]
