# Generated by Django 4.2.6 on 2024-05-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_age'),
        ('api', '0003_alter_daytrack_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytrack',
            name='fats_goal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Fats goal per day (g)'),
        ),
        migrations.AlterField(
            model_name='daytrack',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='track', to='accounts.profile'),
        ),
    ]
