# Generated by Django 4.2.6 on 2024-05-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_daytrack_carbs_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytrack',
            name='calories_goal',
            field=models.DecimalField(decimal_places=0, default=1500, max_digits=6, verbose_name='Energy goal per day (KCAL)'),
        ),
        migrations.AlterField(
            model_name='daytrack',
            name='calories_today',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='kcal'),
        ),
        migrations.AlterField(
            model_name='daytrack',
            name='carbs_goal',
            field=models.DecimalField(decimal_places=1, default=188, max_digits=5, verbose_name='Carbohydrates goal per day (g)'),
        ),
        migrations.AlterField(
            model_name='daytrack',
            name='carbs_today',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='CARBS(g)'),
        ),
        migrations.AlterField(
            model_name='daytrack',
            name='fats_goal',
            field=models.DecimalField(decimal_places=1, default=50, max_digits=5, verbose_name='Fats goal per day (g)'),
        ),
        migrations.AlterField(
            model_name='daytrack',
            name='fats_today',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Fats(g)'),
        ),
        migrations.AlterField(
            model_name='daytrack',
            name='protein_goal',
            field=models.DecimalField(decimal_places=1, default=75, max_digits=5, verbose_name='Protein goal per day (g)'),
        ),
        migrations.AlterField(
            model_name='daytrack',
            name='protein_today',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Protein(g)'),
        ),
    ]
