# Generated by Django 4.2.6 on 2024-07-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('edamam_id', models.CharField(max_length=300, unique=True)),
                ('calories', models.DecimalField(decimal_places=0, default=1500, max_digits=6)),
                ('fats', models.DecimalField(decimal_places=1, default=50, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=1, default=75, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=1, default=188, max_digits=5)),
            ],
        ),
    ]
