# Generated by Django 4.2.6 on 2024-10-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_edamam_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='protein',
            new_name='proteins',
        ),
    ]
