# Generated by Django 4.2.6 on 2024-10-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_protein_recipe_proteins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='proteins',
            new_name='protein',
        ),
    ]
