# Generated by Django 4.2.6 on 2024-10-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_proteins_recipe_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fats',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
