# Generated by Django 4.2.6 on 2024-10-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_weight_alter_recipe_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
