# Generated by Django 4.2.6 on 2024-10-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='protein',
            new_name='proteins',
        ),
    ]
